apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
 name: snap-application
 namespace: app
spec:
 volumeSnapshotClassName: csi-snapclass
 source:
    persistentVolumeClaimName: application
