apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
 name: snap-test
 namespace: application
spec:
 volumeSnapshotClassName: csi-snapclass
 source:
    persistentVolumeClaimName: vol11